# Use Node 18 image
FROM node:18-alpine

# Set work directory
WORKDIR /app

# Install system dependencies
RUN apk add --no-cache git

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Add node_modules to PATH
ENV PATH /app/node_modules/.bin:$PATH

# Copy entrypoint script
COPY ./docker-entrypoint.dev.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]
