version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: erp-backend-dev
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.development
      - DATABASE_URL=postgres://postgres:postgres@db:5432/erp_db_dev
      - REDIS_URL=redis://redis:6379/0
      - DEBUG=1
      - DJANGO_SECRET_KEY=dev_secret_key
      - ALLOWED_HOSTS=localhost,127.0.0.1
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: erp-frontend-dev
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    command: npm start

  db:
    image: postgres:15-alpine
    container_name: erp-db-dev
    environment:
      - POSTGRES_DB=erp_db_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: erp-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data

  mailhog:
    image: mailhog/mailhog
    container_name: erp-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  pgadmin:
    image: dpage/pgadmin4
    container_name: erp-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data_dev:
  redis_data_dev:
  backend_node_modules:
  frontend_node_modules:
