version: '3.8'

services:
  backend:
    build: ./backend
    container_name: erp-backend
    restart: unless-stopped
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.production
      - DATABASE_URL=postgres://postgres:${DB_PASSWORD}@db:5432/erp_db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - db
      - redis
    networks:
      - erp-network

  frontend:
    build: ./frontend
    container_name: erp-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - erp-network

  db:
    image: postgres:15-alpine
    container_name: erp-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=erp_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - erp-network

  redis:
    image: redis:7-alpine
    container_name: erp-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - erp-network

volumes:
  postgres_data:
  redis_data:

networks:
  erp-network:
    driver: bridge
