version: '3.8'

services:
  sonarqube:
    image: sonarqube:latest
    container_name: erp-sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: erp-swagger-editor
    ports:
      - "8081:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: erp-swagger-ui
    ports:
      - "8082:8080"
    environment:
      - API_URL=http://localhost:8000/api/schema/

  portainer:
    image: portainer/portainer-ce
    container_name: erp-portainer
    ports:
      - "9443:9443"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  grafana:
    image: grafana/grafana
    container_name: erp-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    container_name: erp-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  jaeger:
    image: jaegertracing/all-in-one
    container_name: erp-jaeger
    ports:
      - "16686:16686"
      - "14250:14250"

  minio:
    image: minio/minio
    container_name: erp-minio
    ports:
      - "9001:9001"
      - "9000:9000"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: erp-elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    container_name: erp-kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  portainer_data:
  grafana_data:
  prometheus_data:
  minio_data:
  elasticsearch_data:
