apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-backup
  namespace: erp
spec:
  schedule: "0 1 * * *"  # Run at 1 AM daily
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: postgres:15-alpine
            command:
            - /bin/sh
            - -c
            - |
              pg_dump -h erp-db -U postgres -d erp_db -F c -f /backup/erp_db_$(date +%Y%m%d_%H%M%S).dump
              aws s3 cp /backup/*.dump s3://your-bucket/backups/
              rm -f /backup/*.dump
            env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: erp-secrets
                  key: db-password
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secret-key
            volumeMounts:
            - name: backup
              mountPath: /backup
          volumes:
          - name: backup
            emptyDir: {}
          restartPolicy: OnFailure
