apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: erp-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: erp-backend
  endpoints:
  - port: metrics
    interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: erp-alerts
  namespace: monitoring
spec:
  groups:
  - name: erp
    rules:
    - alert: HighErrorRate
      expr: |
        sum(rate(http_requests_total{status=~"5.."}[5m])) 
        / 
        sum(rate(http_requests_total[5m])) > 0.1
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: High HTTP error rate
        description: Error rate is above 10% for the last 5 minutes
    
    - alert: HighLatency
      expr: |
        histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) > 2
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High latency
        description: 95th percentile latency is above 2 seconds
    
    - alert: HighMemoryUsage
      expr: |
        container_memory_usage_bytes{container=~"erp-.*"} 
        / 
        container_spec_memory_limit_bytes{container=~"erp-.*"} > 0.85
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: High memory usage
        description: Container memory usage is above 85% for 15 minutes
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: erp-ingress
  namespace: erp
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - your-domain.com
    secretName: erp-tls
  rules:
  - host: your-domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: erp-frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: erp-backend
            port:
              number: 8000
