apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
metadata:
  name: erp-encryption-config
spec:
  resources:
    - resources:
        - secrets
      providers:
        - aescbc:
            keys:
              - name: key1
                secret: ${ENCRYPTION_KEY}
        - identity: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: erp-encryption-key
  namespace: erp
type: Opaque
data:
  key: ${BASE64_ENCRYPTION_KEY}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-encryption-reader
  namespace: erp
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  resourceNames: ["erp-encryption-key"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-encryption-reader-binding
  namespace: erp
subjects:
- kind: ServiceAccount
  name: erp-backend
  namespace: erp
roleRef:
  kind: Role
  name: secret-encryption-reader
  apiGroup: rbac.authorization.k8s.io
