apiVersion: v1
kind: ConfigMap
metadata:
  name: advanced-predictions
  namespace: analytics
data:
  prediksi_cuaca.yaml: |
    model:
      nama: "PrediksiDampakCuaca"
      parameter:
        - nama: "curah_hujan"
          metode: "ensemble_forecast"
          interval: "per_jam"
        - nama: "kecepatan_angin"
          metode: "neural_network"
          interval: "real_time"
      dampak_analisis:
        - aspek: "jadwal_kerja"
          faktor:
            - "keterlambatan_potensial"
            - "produktivitas_pekerja"
        - aspek: "keselamatan"
          faktor:
            - "risiko_operasional"
            - "kondisi_berbahaya"

  prediksi_produktivitas.yaml: |
    model:
      nama: "OptimalisasiProduktivitas"
      parameter:
        - nama: "kinerja_tim"
          variabel:
            - "komposisi_tim"
            - "pengalaman"
            - "kondisi_lapangan"
        - nama: "efisiensi_peralatan"
          variabel:
            - "utilisasi"
            - "downtime"
            - "maintenance_schedule"
      optimasi:
        metode: "reinforcement_learning"
        target: "maksimum_output"

  prediksi_kualitas.yaml: |
    model:
      nama: "PrediksiKualitasKonstruksi"
      komponen:
        - nama: "analisis_material"
          parameter:
            - "kualitas_input"
            - "kondisi_penyimpanan"
            - "metode_penanganan"
        - nama: "metode_konstruksi"
          parameter:
            - "teknik_pelaksanaan"
            - "kompetensi_pekerja"
            - "kondisi_lingkungan"
      pembelajaran:
        metode: "deep_learning"
        dataset: "historical_quality_data"

  prediksi_biaya.yaml: |
    model:
      nama: "EstimasiBiayaAkurat"
      parameter:
        - nama: "analisis_pasar"
          variabel:
            - "harga_material"
            - "upah_pekerja"
            - "biaya_peralatan"
        - nama: "faktor_eksternal"
          variabel:
            - "kondisi_ekonomi"
            - "regulasi"
            - "kompetisi_pasar"
      prediksi:
        metode: "hybrid_ml"
        interval: "mingguan"
